# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd8913eb7eb5e053d1081b26579090d05b89984cb70726444578fa6f828a07608ec94b1580be0a59548567f316377fab6cb3c1f79b4683000eef2b0cc4bb786b

test:
  secret_key_base: 4abad10604a1938be50503d4ae5cb5b353afd7e1716557ed1acfe1404dec4b09ad332d111ff655b5636b0381e8d85ac79a8e0ac84f15f0161e28b4f438e34f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
